name: _laconic_workspace
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

workspace:
  - packages/laconic
  - packages/laconic_sqlite
  - packages/laconic_mysql
  - packages/laconic_postgresql
