name: laconic_sqlite
description: SQLite driver for the Laconic query builder.
version: 1.0.1
homepage: https://github.com/CalsRanna/laconic
repository: https://github.com/CalsRanna/laconic

environment:
  sdk: '>=3.7.0 <4.0.0'

resolution: workspace

dependencies:
  laconic: ^2.0.0
  sqlite3: ^2.7.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
